name: naksha-api
services:
- name: api
  source_dir: /
  github:
    repo: Abransh/Naksha
    branch: main
  build_command: ./build.sh
  run_command: cd apps/api && npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8000"

databases:
- name: db
  engine: PG
  version: "15"
  size: basic

- name: redis
  engine: REDIS
  version: "7"
  size: basic