name: nakksha-consulting-api
services:
- name: api
  source_dir: /
  github:
    repo: Abransh/Naksha
    branch: main
  run_command: cd apps/api && npm start
  build_command: |
    npm install
    cd packages/database && npm install && npm run build
    cd ../../apps/api && npm install && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8000"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: REDIS_URL
    value: ${redis.REDIS_URL}
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: JWT_REFRESH_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_HOST
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_PORT
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_USER
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_PASS
    scope: RUN_TIME
    type: SECRET
  - key: CLOUDINARY_CLOUD_NAME
    scope: RUN_TIME
    type: SECRET
  - key: CLOUDINARY_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: CLOUDINARY_API_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: RAZORPAY_KEY_ID
    scope: RUN_TIME
    type: SECRET
  - key: RAZORPAY_KEY_SECRET
    scope: RUN_TIME
    type: SECRET

databases:
- name: db
  engine: PG
  version: "17"
  size: basic
  num_nodes: 1

- name: redis
  engine: REDIS
  version: "7"
  size: basic
  num_nodes: 1